#!/usr/bin/bash
color=${color:-white}
color_charging=${color_charging:-green}
color_discharging=${color_discharging:-red}
wrap_in_brackets=${wrap_in_brackets:-false}

PERCENTAGE=""
STATUS=""
POWERMODE="$(powerprofilesctl get)"
case "$POWERMODE" in
    "power-saver")
        POWERMODE="<span foreground=\"#fabd2f\">󰢟</span>"
        ;;
    "balanced")
        POWERMODE="<span foreground=\"#ebddb2\">󰢟</span>"
        ;;
    "performance")
        POWERMODE="<span foreground=\"$color_discharging\">󱊦</span>"
        ;;
esac

SOURCES=$(ls /sys/class/power_supply | grep BAT)
[[ -z "$SOURCES" ]] && exit 1 # Any battery in the machine?

BATTERIES=($SOURCES)
for BATTERY in "${BATTERIES[@]}"
do
    DATA="/sys/class/power_supply/$BATTERY"
    CAP=$(cat "$DATA/capacity")
    STATUS=$(cat "$DATA/status")

    ARROW=''
    if [[ $STATUS == "Discharging" ]]; then
        ARROW="<span foreground=\"$color_discharging\">▼</span>"
    elif [[ $STATUS == "Charging" ]]; then
        ARROW="<span foreground=\"$color_charging\">▲</span>"
    fi

    PERCENTAGE="$PERCENTAGE $ARROW<span foreground=\"$color\">$CAP%</span>"
    INFO="<span foreground=\"$color\">$INFO $BATTERY: $STATUS</span>"
done

if [[ "$wrap_in_brackets" == "true" ]]; then
    INFO="[ $INFO ]"
    PERCENTAGE="[ $PERCENTAGE $POWERMODE ]"
fi

if [[ "$button" -eq 1 ]]; then
    echo $INFO
else
    echo $PERCENTAGE
fi
