#!/usr/bin/bash

case "$BLOCK_BUTTON" in
    1) blueberry
esac

bluetooth_powered=$(bluetoothctl show | grep Powered | awk '{print $2}')

if [[ "$bluetooth_powered" == "yes" ]]; then
    echo "󰂯"
    exit
fi

echo "<span foreground=\"#fb4833\">󰂲</span>"
