#!/usr/bin/bash

case "$BLOCK_BUTTON" in
    # Left click
    1) pavucontrol ;;
    # Scroll click
    #2) pavucontrol ;;
    # Right click
    3) swayosd-client --output-volume mute-toggle ;;
    # Scroll up
    4) swayosd-client --output-volume raise ;;
    # Scoll down
    5) swayosd-client --output-volume lower ;;
esac

volume=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print substr($5, 0, length($5) - 1)}')
muted=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print substr($0,7)}')

volume_icon=""
if [[ "$muted" == "no" ]]; then
    [[ $volume -le 60 ]] && volume_icon="󰕾"
    [[ $volume -le 30 ]] && volume_icon=""
else
    volume_icon="<span foreground=\"#fb4833\">󰖁</span>"
fi

bluetooth_connected=$(pactl get-default-sink | grep "bluez" | awk '{ if ($1 != "") { print "yes"} }')
if [[ "$bluetooth_connected" == "yes" ]]; then
    volume_icon="<span foreground=\"#83a598\"></span> $volume_icon"
fi

microphone_icon="󰍬"
microphone_muted=$(pactl get-source-mute @DEFAULT_SOURCE@ | awk '{print substr($0,7)}')
if [[ "$microphone_muted" == "yes" ]]; then
    microphone_muted="<span foreground=\"#fb4833\">󰍭</span>"
fi

echo "[$microphone_icon $volume_icon $volume%]"
